#!/bin/sh
#
# Front-end to incus to manage a bunch of development containers
#
# Copyright (C) 2012 Jamie Lentin <jm@lentin.co.uk>
#
# This file is licensed under the terms of the GNU General Public
# License version 2.  This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
set -eu

maximise_menu () {
    stty size | awk '// { print $1 - 3 " " $2 - 6 " " $2 - 6 }'
}

term_title () {
    printf "\033]0;%s: %s\007" "$(hostname -f)" "$1"
}

while true; do
    # Choose a container
    term_title "Incus containers"
    # NB: Multiple IP address spew onto several lines, filter them
    # shellcheck disable=SC2046
    container=$(dialog \
        --menu "Available containers (esc-esc to refresh, cancel to quit)" $(maximise_menu) \
        $(incus list -fcompact,noheader --columns=ns4 | awk '!/^\s\W/ { print $1 " " $2 ($3 ? "/" $3 : "") }' | sort -k1) \
        3>&1 1>&2 2>&3 || echo "(ERR:$?)")
    echo
    [ "${container}" = "(ERR:1)" ] && exit 0 # Cancel
    [ "${container}" = "(ERR:255)" ] && continue # Timeout / escape-escape

    # Get the status of the given container, show menu based on current state
    container_status=$(incus info "$container" \
        | awk '/^Status:/ { print $2 }')

    menu_title="Container $container currently $container_status"
    case $container_status in
    RUNNING)
        # shellcheck disable=SC2046
        container_operation=$(dialog --menu "$menu_title" $(maximise_menu) \
            attach "" \
            freeze "" \
            upgrade "" \
            console "" \
            stop "" \
            3>&1 1>&2 2>&3 || echo "cancel")
        ;;
    FROZEN)
        container_operation="unfreeze"
        ;;
    STOPPED)
        # shellcheck disable=SC2046
        container_operation=$(dialog --menu "$menu_title" $(maximise_menu) \
            start "" \
            rename "" \
            "edit-config" "" \
            clone "" \
            copy "" \
            3>&1 1>&2 2>&3 || echo "cancel")
        ;;
    *)
        echo "Unknown container state $container_status"
        sleep 3
        ;;
    esac
    [ -z "$container_operation" ] && continue

    case $container_operation in
    attach)
        clear
        term_title "Incus container shell: ${container}"
        incus exec "${container}" --env TERM=xterm /bin/bash || sleep 3
        ;;
    upgrade)
        clear
        term_title "Incus apt upgrade: ${container}"
        incus exec "${container}" -- /bin/sh -c "/usr/bin/apt update ; /usr/bin/apt upgrade && /usr/bin/apt autoremove" || sleep 3
        ;;
    edit-config)
        incus config edit "${container}" || sleep 3
        ;;
    rename)
        container_new="$(dialog --inputbox "New container name" 0 0 "${container}" \
            3>&1 1>&2 2>&3 || echo "")"
        [ -z "${container_new}" ] && continue
        [ -n "$(incus list -fcompact,noheader -cn "^${container_new}"'$')" ] && { echo "${container_new} Already exists!"; sleep 3 ; continue; }
        incus rename "${container}" "${container_new}"

        echo "${container_new}" | incus file edit "${container_new}/etc/hostname" || sleep 3
        ;;
    clone)
        container_new="$(dialog --inputbox "New container name" 0 0 "" \
            3>&1 1>&2 2>&3 || echo "")"
        [ -z "${container_new}" ] && continue
        incus copy "${container}" "${container_new}" || sleep 3

        echo "${container_new}" | incus file edit "${container_new}/etc/hostname" || sleep 3
        ;;
    copy)
        # shellcheck disable=SC2046
        remote_name=$(dialog --menu "Remote to send to" $(maximise_menu) \
            $(incus remote list -fcompact,noheader --columns=aun | awk '/^\s+tls/ { print $3 " " $2 }') \
            3>&1 1>&2 2>&3 || echo "")
        [ -z "${remote_name}" ] && continue

        incus copy "${container}" "${remote_name}:${container}" --instance-only || sleep 3
        ;;
    cancel)
        # Do nothing, return to main menu
        ;;
    *)
        echo "Running incus ${container_operation} ${container}..."
        incus "${container_operation}" "${container}" || sleep 3
        ;;
    esac
done
